---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Common tests
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # Docker
#   - repo: https://github.com/hadolint/hadolint
#     rev: v2.10.0
#     hooks:
#       - id: hadolint
  # YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: ["-d", "relaxed"]
  # Shell
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
  # TERRAFORM ##################################################################
#   - repo: https://github.com/gruntwork-io/pre-commit
#     rev: v0.1.17
#     hooks:
#       - id: terraform-fmt
# #      - id: terraform-validate
#       - id: tflint
#   - repo: https://github.com/terraform-docs/terraform-docs
#     rev: v0.16.0
#     hooks:
#       - id: terraform-docs-go
#         args: ["markdown", "table", "--output-file", "README.md", "--output-mode","inject", "examples/tf_module/."]
